#database containing master aggregation addresses
data:
#  host: REDACTED
#  port: REDACTED
#  db: REDACTED
  user: REDACTED
  password: REDACTED

scrubber:
  javaRelativeDirs:
    - assets
    - streams
  ttlSeconds: 3600
  
#used for connecting to 3rd party services if needed
jerseyClient:
  timeout: 100ms
  connectionTimeout: 100ms
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: false
  gzipEnabledForRequests: false
  chunkedEncodingEnabled: false
  
loadbalCommunicator:
  port: REDACTED
  bootPath: /cloud/boot
  keepAlivePath: /cloud/keepAlive
  eventPath: /cloud/playerEvent
  loadbalURL: REDACTED
  
server:
  gzip:
      enabled: false
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
      outputBufferSize: 128MiB
      minBufferPoolSize: 4096KiB
      bufferPoolIncrement: 8192KiB
      maxBufferPoolSize: 256MiB

  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 3034

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ALL

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.apmasphere.billproto' to DEBUG.
    com.apmasphere.billproto: DEBUG

    org.hibernate.SQL: ALL

  appenders:
    - type: console
